services:
  - type: web
    name: safe-nation-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    nodeVersion: 18
    envVars:
      - key: VITE_API_URL
        value: https://safe-nation-otp-backend.onrender.com
